### PR TITLE
Parser should allow %{v} macro_string

### PR DESCRIPTION
**Pull request by rfgil**
Hi! Thank you for this gem.

I noticed the gem is failing to parse the following SPF Record: `v=spf1 include:%{ir}.%{v}.%{d}.spf.has.pphosted.com -all`:

```
DEVELOPMENT irb(main):001> SPF::Query::Parser.parse("v=spf1 include:%{ir}.%{v}.%{d}.spf.has.pphosted.com -all")
/Users/rafael/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/parslet-1.8.2/lib/parslet/cause.rb:70:in `raise': Failed to match sequence (VERSION SP{1, } rules:TERMS SP{0, }) at line 1 char 22. (Parslet::ParseFailed)
```

This is because the parser is not expecting the `%{v}` macro, which is valid according to the documentation: https://datatracker.ietf.org/doc/html/rfc7208#section-7.4.

Thus, this PR adds the missing `v` as a valid `macro_letter`.

### CODE REVIEW

**Comment by woodruffw** [comment]
Thanks @rfgil! This looks reasonable to me.

**Comment by woodruffw** [comment]
Would you mind adding some tests as well?

**Comment by rfgil** [comment]
> Would you mind adding some tests as well?

@woodruffw Sure, just added a spec with the SPF record above. Let me know if it's as you expected. Thanks!

**Comment by woodruffw** [comment]
Yep, LGTM. Thanks @rfgil!

**Review by woodruffw — APPROVED** [review]

**Pull request merged**
